DROP POLICY IF EXISTS "roommates_select" ON public.roommates;
DROP POLICY IF EXISTS "roommates_update" ON public.roommates;
DROP POLICY IF EXISTS "inventory_items_all" ON public.inventory_items;
DROP POLICY IF EXISTS "inventory_transactions_select" ON public.inventory_transactions;
DROP POLICY IF EXISTS "inventory_transactions_insert" ON public.inventory_transactions;
DROP POLICY IF EXISTS "shopping_items_select" ON public.shopping_items;
DROP POLICY IF EXISTS "shopping_items_insert" ON public.shopping_items;
DROP POLICY IF EXISTS "shopping_items_update" ON public.shopping_items;
DROP POLICY IF EXISTS "expenses_all" ON public.expenses;
DROP POLICY IF EXISTS "expense_splits_all" ON public.expense_splits;
DROP POLICY IF EXISTS "settlements_all" ON public.settlements;
DROP POLICY IF EXISTS "recurring_expenses_all" ON public.recurring_expenses;
DROP POLICY IF EXISTS "chore_templates_all" ON public.chore_templates;
DROP POLICY IF EXISTS "chore_rotations_all" ON public.chore_rotations;
DROP POLICY IF EXISTS "chore_assignments_all" ON public.chore_assignments;
DROP POLICY IF EXISTS "concerns_all" ON public.concerns;
DROP POLICY IF EXISTS "concern_comments_all" ON public.concern_comments;
DROP POLICY IF EXISTS "concern_attachments_all" ON public.concern_attachments;
DROP POLICY IF EXISTS "notifications_select" ON public.notifications;
DROP POLICY IF EXISTS "notifications_update" ON public.notifications;
DROP POLICY IF EXISTS "push_subscriptions_all" ON public.push_subscriptions;
DROP POLICY IF EXISTS "recipes_all" ON public.recipes;
DROP POLICY IF EXISTS "recipe_ingredients_all" ON public.recipe_ingredients;
DROP POLICY IF EXISTS concern_photos_select ON storage.objects;
DROP POLICY IF EXISTS concern_photos_insert ON storage.objects;

REVOKE ALL ON TABLE public.roommates FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.inventory_items FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.inventory_transactions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.shopping_items FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.expenses FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.expense_splits FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.settlements FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.recurring_expenses FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.chore_templates FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.chore_rotations FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.chore_assignments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.concerns FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.concern_comments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.concern_attachments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.notifications FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.push_subscriptions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.recipes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.recipe_ingredients FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE storage.objects FROM anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.adjust_inventory(uuid, uuid, text, numeric, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.purchase_shopping_item(uuid, uuid, numeric) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.save_expense(uuid, text, text, numeric, uuid, text, text, date, uuid, jsonb, boolean, uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_settlement(uuid, uuid, numeric, text, uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_due_recurring_expenses() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_due_chore_assignments() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.complete_chore_assignment(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_time_notifications() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_push_notifications() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.ack_push_notification(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.apartment_balances() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.apartment_today() FROM PUBLIC, anon, authenticated;
